import Head from 'next/head'
import Link from 'next/link';
import { blogPosts } from '../lib/data'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Markdown blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 >
         My blog
        </h1>
      </main>
      <div>
        {blogPosts.map((item) => (
          <div key={item.slug}>
          <Link href={`/blog/${item.slug}`}>
          <a><div>{item.title}</div></a>
          </Link>
          <div>{item.date.toString()}</div>
           <div>{item.content}</div>
          </div>
        ))
        }
      </div>

    </div>
  )
}
